frontend:
  image: frontend-image
  replicas: 2
  port: 5002

backend:
  image: backend-image
  replicas: 2
  port: 5001
  mysqlCreds:
    dbHost: "mysqlclusterip"
    PASSWORD: "123456"
    DATABASE: "crypto_db"

mysql:
  image: mysql:5.7
  replicas: 1
  port: 3306
  mysqlCreds:
    MYSQL_ROOT_PASSWORD: "123456"
    MYSQL_DATABASE: "crypto_db"

services:
  frontLoadBalancer:
      type: LoadBalancer
      port: 80
      targetPort: 5002

  beclusterip:
    type: ClusterIP
    port: 5001
    targetPort: 5001
  
  mysqlclusterip:
    type: ClusterIP
    port: 3306
    targetPort: 3306