apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers: 
      - name: mysql
        image: {{ .Values.mysql.image }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.mysqlCreds.MYSQL_ROOT_PASSWORD | quote }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.mysqlCreds.MYSQL_DATABASE | quote }}
        ports:
        - containerPort: {{ .Values.mysql.port }}