apiVersion: v1
kind: Service
metadata:
  name: frontloadbalancer
spec:
  selector:
    app: frontend 
  type: {{ .Values.services.frontLoadBalancer.type }}
  ports:
  - port: {{ .Values.services.frontLoadBalancer.port }}
    targetPort: {{ .Values.services.frontLoadBalancer.targetPort }}