apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers: 
      - name: mysql
        image: mysql:5.7
        env: # i need both env vars here and in the mysql deployment so the be will know where to connect and the mysql will know what to create
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: MYSQL_DATABASE
          value: "crypto_db"
        ports:
        - containerPort: 3306