apiVersion: v1
kind: Service
metadata:
  name: frontloadbalancer
spec:
  selector:
    app: frontend # this needs to be the name of the fe deployment app because thats the label the servie look for to match itself to
  type: LoadBalancer
  ports:
    # port that service is exposed on the outside
  - port: 80
    # port that the service listen to internally
    targetPort: 5002