apiVersion: v1
kind: Service
metadata:
# this need to be named backend-service becuase in the fe pyhton code it try to reach service named backend-service and becuase in kubernetes the fe go to my be cluster ip i need to name it backend-service
  name: backend-service  
spec:
  selector:
    app: backend # this needs to be the name of the be deployment app because thats the label the servie look for to match itself to
  type: ClusterIP
  ports:
  - port: 5001
    targetPort: 5001